import random
a = random.randrange(1,6)
print("Pierwszy rzut kostką: " ,end="")
print(a)
b = random.randrange(1,6)
print("Pierwszy rzut kostką: " ,end="")
print(b)
c = random.randrange(1,6)
print("Pierwszy rzut kostką: " ,end="")
print(c)
print("Suma rzutów to:" ,end="")
print(a+b+c)