tab=[12,6,4,9,10]
print(tab[0] ,end="")
print(": " ,end="")
print(int(tab[0])*"*")
print(tab[1] ,end="")
print(": " ,end="")
print(int(tab[1])*"*")
print(tab[2] ,end="")
print(": " ,end="")
print(int(tab[2])*"*")
print(tab[3] ,end="")
print(": " ,end="")
print(int(tab[3])*"*")
print(tab[4] ,end="")
print(": " ,end="")
print(int(tab[4])*"*")